config/routes.rb
Rails.application.routes.draw do

  resources :playlists
  resources :songs
  resources :users, :except => [:new, :index]
  get '/users/:id/favorite', to: 'users#favorite'
  put '/users/follow/:id', to: 'users#follow'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  root 'session#new'
  post '/playlists/add_song', to: 'playlists#add_song'
  get '/playlists/remove/:song_id/:playlist_id', to: 'playlists#remove'
  get '/songs/favorite/:song_id', to: 'songs#favorite'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  def new
	redirect_to user_path(current_user) if logged_in?
	@user = User.new
  end

  def create
  	user = User.find_by(username: params[:session][:username])
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		redirect_to user
  	else
		@user = User.new
  		@errorsConnect = 'Les identifiants sont incorrectes'
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_url
  end

end

app/helpers/session_helper.rb
module SessionHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def correct_user?
		params[:id].to_i == current_user.id
	end

	def require_login
		unless logged_in?
			flash[:notice] = 'You are not authorized to access this page, please log in'
			redirect_to root_path
		end
	end

	def is_owner
      if !correct_user?
        flash[:notice] = 'You are not authorized to access this page'
        redirect_to user_path(current_user)
      end
    end

    def owner?(stuff)
		stuff.user == current_user
    end

end

app/views/session/new.html.erb
 <div class="head-logo">
    <%= image_tag('zikror.png') %>
  </div>
  <div class="content-page-login">
  <div class="container-login">
    <div class="row-login">
      <div class="col-md-5 signin-form form-content">
        <header>
          <span class="answer">Vous avez un compte ?</span><br/>
          Connectez-vous et profitez<br/> pleinement de vos musiques
        </header>
        <%= form_for(:session, class: "form-group form-horizontal", url: login_path) do |f| %>
          <%= f.text_field :username, class: 'form-control', placeholder: "Nom d'utilisateur" %>
          <%= f.password_field :password, class: 'form-control', placeholder: "Mot de passe" %>
          <div class="errorConnect"><%= @errorsConnect %></div>
          <%= f.submit "Log in", class: "btn-validation", value: "VALIDER" %>
        <% end %>
      </div>
      <div class="col-md-2 col-sm-12 separate-form">
        <span class="vertical-barre"></span>
          <p>OU</p>
        <span class="vertical-barre"></span>
      </div>
      <div class="col-md-5 col-sm-12 signup-form form-content">
        <header>
          <span class="answer">Pas encore de compte ?</span><br/>
          Inscrivez-vous c'est gratuit !
        </header>
          <%= form_for(@user, class: "form-group form-horizontal") do |f| %>
           <%= f.text_field :username, class: 'form-control', placeholder: "Nom d'utilisateur*" %>
            <div class="error"><%= @user.errors[:username].first if @user.errors.any? %></div>

            <%= f.email_field :mail, class: 'form-control', placeholder: "Adresse email*" %>
            <div class="error"><%= @user.errors[:mail].first if @user.errors.any? %></div>

            <%= f.password_field :password, class: 'form-control', placeholder: "Mot de passe*" %>
            <div class="error"><%= @user.errors[:password].first if @user.errors.any? %></div>

            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Confirmez votre mot de passe*" %>
            <div class="error"><%= @user.errors[:password_confirmation].first if @user.errors.any? %></div>

          <%= f.submit "Create my account", class: "btn-validation", value: "VALIDER" %>
        <% end %>
        
        <span class="indication">* Tout les champs sont obligatoires</span>
      </div>
    </div>
  </div>
  </div>