config/routes.rb
Rails.application.routes.draw do

  resources :playlists
  resources :songs
  resources :users, :except => [:new, :index]
  get '/users/:id/favorite', to: 'users#favorite'
  put '/users/follow/:id', to: 'users#follow'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  root 'session#new'
  post '/playlists/add_song', to: 'playlists#add_song'
  get '/playlists/remove/:song_id/:playlist_id', to: 'playlists#remove'
  get '/songs/favorite/:song_id', to: 'songs#favorite'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_player.html.erb
<% continue ||= false %>
<div class="audio">
	<% unless songs.empty? %>
		<audio id="mejs" src="/PETIT_BISCUIT_Sunset_Lover.mp3" class="mejs__player"></audio>
		<form>
			<div id="player-checkbox">
				<input type="radio" name="play_mode" id="continue" <%= "checked" if continue %>>
				<label for="continue">Lecture continue</label>
				<input type="radio" name="play_mode" id="shuffle">
				<label for="shuffle">Aléatoire</label>
			</div>
		</form>
	<% end %>
</div>

app/views/shared/_right_sidebar.html.erb
<% data ||= false  %>
<%= form_tag(request.env['PATH_INFO'], method: 'get', class: "form-search form-search-profil") do %>
<div class="form-group">
	<%= search_field_tag(:username, params[:username] || '', name: 'username', placeholder: 'Recherche de profil') %>
	<button type="submit"><%= image_tag('search.png') %></button>
</div>
<% end %>
<div class="center-vertical">
	<ul class="right-tabs nav nav-tabs">
		<li class="active"><a data-toggle="tab" href="#right-profil">PROFIL</a></li>
		<li><a data-toggle="tab" href="#right-parcourir">PARCOURIR</a></li>
		<% if data %>
			<li><a data-toggle="tab" href="#right-stats">STATS</a></li>
		<% end %>
	</ul>
	<div class="bloc-bottom tab-content">
		<div id="right-profil" class="tab-pane fade in active">
			<div class="avatar-profil" style="background: url(<%= gravatar_src(user) %>); background-size: cover"></div>
			<span class="username"><%= user.username %></span>
			<p class="description-profil"><%= user.description %></p>
			<% if user != current_user %>
				<% follow_link_text = current_user.follow?(user) ? "Ne plus suivre" : "Suivre" %>
				<%= link_to follow_link_text, "/users/follow/#{user.id}" ,class: 'follow-button', method: :put, remote: true %>
			<% end %>
			<div class="bloc-pop">
				<span tabindex="0" class="glyphicon glyphicon-option-horizontal" data-trigger="focus" data-toggle="popover" data-content="Email : <%= user.mail %>"></span>
			</div>
			<div class="button">
				<%= link_to 'mon compte'.upcase, edit_user_path(current_user) %>
			</div>
		</div>
		<ul id="right-parcourir" class="list-all-profil tab-pane fade active">
			<% User.where("username LIKE ?", "%#{params[:username]}%").each do |user| %>
			<div>
				<li><%= gravatar(user, 40) %></li>
				<li class="title-user"><%= link_to user.username, user %></li>
				<li><%= user.description %></li>
				<div class="action-sidebar-profil">
					<% if current_user == user %>
					<li><%= link_to 'Edit', edit_user_path(user) %></li>
					<% end %>
					<% if current_user.admin %>
					<li><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></li>
					<% end %>
				</div>
			</div>
			<% end %>
	    </ul>
	    <div id="right-stats" class="tab-pane fade in active">
	    	<h5>Genre %</h5>
	    	<div id="chart-genre" style="height: 250px;"></div>
		</div>
	</div>
</div>
<div class="info-user-pop popover">
<span><b>Email</b> : <%= user.mail %></span>
<span><b>Inscrit le</b> : <%= user.created_at.strftime("%d-%m-%Y") %></span>
<span><b>Musiques</b> : <%= user.songs.size %></span>
</div>
<div class="deconnect-profil">
	<%= image_tag('logout.png') %>
	<span class="span-deconnect"><%= link_to "Deconnexion", logout_path, :method => "delete" %></span>
</div>

<script type="text/javascript">
$(document).on('ajax:success', '.follow-button', function(status, data, xhr){
	return $('.follow-button').text($('.follow-button').text() == 'Suivre' ? 'Ne plus suivre' : 'Suivre');
});
</script>

<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>	
<script>	
// Copyright (c) 2013, Olly Smith
// All rights reserved.
Morris.Donut({
  element: 'chart-genre',
  data: <%= raw(getData(data)) if data %>,
  colors : ['#D24D57', '#D91E18', '#96281B', '#EF4836', '#D64541', '#C0392B', '#CF000F', '#EC644B']
});

$("#chart-genre svg text").attr('fill', "#8e8e8e");

</script>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
	<div class="block-logo">
		<%= image_tag('logo-zkr.png') %>
	</div>
	<div class="container-list">
		<div class="list-sidemenu-music">
			<ul>
				<li>
					<span class="head-list">MES MUSIQUES</span>
					<ul class="filter-list">
						<li><a href="">Toutes</a></li>
						<!-- <li><a href="">Artistes</a></li>
						<li><a href="">Genre</a></li> -->
						<li><%= link_to "Favorites", "/users/#{current_user.id}/favorite" %></li>
					</ul>
				</li>
			</ul>
		</div>

		<div class="list-sidemenu-music second-list">
			<ul>
				<li>
					<span class="head-list">MES PLAYLISTS</span>
					<ul class="filter-list">
						<% current_user.playlists.each do |playlist| %>
							<li class="list-playlist"><%= link_to playlist.name, playlist_path(playlist) %></li>
						<% end %>
					</ul>
				</li>
			</ul>
		</div>
	</div>
	<div class="add-playlist">
	<%= image_tag('add.png') %>
		<%= link_to image_tag('music-player.png'), new_song_path, class: "link-add-music" %><span>Ajouter une musique</span>
		<%= link_to image_tag('playlist.png'), new_playlist_path, class: "link-add-playlist" %><span>Ajouter une playlist</span>
	</div>
</div>

app/views/shared/_song_search.html.erb
<%= form_tag('/songs', method: 'get', class: "form-search form-search-musique") do %>
  <div class="form-group">
  <%= search_field_tag(:query, params[:query] || '', list: 'datas', placeholder: 'Rechercher un titre') %>
  <datalist id="datas">
    <% Song.pluck(:artist, :title).flatten.uniq.each do |d| %>
      <option value="<%= d %>">
    <% end %>
  </datalist>
  <%= select_tag(:genre, options_for_select(["Genre"] + Song.all.pluck(:genre).uniq, params[:genre]))%>
  <button type="submit"><%= image_tag('search.png') %></button>
  </div>
<% end %>

app/views/shared/_songs_list.html.erb
<table class="table musique ctn-musique table-profil">
	<thead>
		<tr class="disabled-tr">
			<th class="index-th">#</th>
			<th class="favoris-th"></th>
			<th class="action-music"></th>
			<th>Titre</th>
			<th>Artiste</th>
			<th>Genre</th>
			<th>Année</th>
			<th class="last-th">Actions</th>
		</tr>
		<tbody>
			<% songs.each_with_index do |song, key| %>
				<% if !song.private || song.user == current_user %>
					<tr>
						<td><%= key+1 %></td>
						<td>
							<% if has_favorite(song) %>
								<%= link_to image_tag('like_red.png'), '#', class: "action-zik favorite", 'title': 'Retirer des favoris', data: {:song => song.id, :toggle => 'tooltip'} %>
							<% else %>
								<%= link_to image_tag('like.png'), '#', class: "action-zik favorite", 'title': "Ajouter aux favoris", data: {:song => song.id, :toggle => 'tooltip'} %>
							<% end %>
						</td>
						<td class="th-music">
							<%= image_tag('play-button.png', class: "play-music", :data => { :music => song.file.url, :index => key }) %>
						</td>
						<td><%= link_to song.title, song_path(song) %></td>
						<td><%= song.artist %></td>
						<td><%= song.genre %></td>
						<td><%= song.year %></td>
						<td class="th-action">
							<span data-toggle="tooltip" title='Ajouter à une playlist'> <a data-song="<%= song.id %>" data-toggle="modal" data-target="#exampleModalLong" class="action-zik"><%= image_tag('playlist.png') %></a> </span>
							<a href="<%= song.file.url %>" data-toggle="tooltip" title="Télécharger" class="action-zik" download><%= image_tag('download-arrow.png') %></a>
							<% if owner?(song) %>
								<%= link_to image_tag('new-file.png'), edit_song_path(song) ,class: "action-zik", 'data-toggle': "tooltip", 'title': "Editer" %>
								<% if playlist %>
									<%= link_to raw(image_tag('delete-button.png')), { action: "remove", song_id: song.id, playlist_id: @playlist.id }, class: "action-zik", 'data-toggle': "tooltip", 'title': "Supprimer", data: { confirm: "Êtes-vous certain de vouloir supprimer #{song.title} de cette playlist ?" } %>
								<% else %>
									<%= link_to image_tag('delete-button.png'), song, class: "action-zik", 'data-toggle': "tooltip", 'title': "Supprimer", method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer cette musique ?' } %>
								<% end %>
							<% end %>
						</td>
					</tr>	
				<% end %>	
			<% end %>
		</tbody>
	</thead>
</table>

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="exampleModalLongTitle">Ajouter à une playlist</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p>Choisissez une playlist:</p>
				<%= form_tag("/add_song", method: "post", id: "add_song") do %>
				<%= select_tag(:playlist_id, options_for_select(current_user.playlists.collect{|p| [p.name, p.id]}))%>
				<button type="submit">AJOUTER</button>
				<% end %>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">ANNULER</button>
			</div>
		</div>
	</div>
</div>

app/views/shared/_user_badge.html.erb
<% edit ||= false %>
<div class="avatar <%= 'avatar-edit' if edit %>">
	<figure style="background-image: url(<%= gravatar_src(current_user) %>); background-size: cover;"></figure>
	<span><%= link_to current_user.username, user_path(current_user) %></span>
</div>