config/routes.rb
Rails.application.routes.draw do

  resources :playlists
  resources :songs
  resources :users, :except => [:new, :index]
  get '/users/:id/favorite', to: 'users#favorite'
  put '/users/follow/:id', to: 'users#follow'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  root 'session#new'
  post '/playlists/add_song', to: 'playlists#add_song'
  get '/playlists/remove/:song_id/:playlist_id', to: 'playlists#remove'
  get '/songs/favorite/:song_id', to: 'songs#favorite'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/playlist.rb
class Playlist < ApplicationRecord
	belongs_to :user
	has_many :playlist_songs
	has_many :songs, through: :playlist_songs
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"],
	message: 'File must an image'

	validates :name,
				presence: true,
				uniqueness: true,
				length: {maximum: 20}

	validates :description,
				length: {maximum: 256}

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:add_song]
  before_action :require_login
  before_action :check_owner, only: [:edit, :update]
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists =  Playlist.where("name LIKE ?", "%#{params[:playlist_name]}%")
     unless params[:username].nil?
      @users_list =  User.where("username LIKE ?", "%#{params[:username]}%")
    else
      @users_list = User.all()
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    # @playlist = Playlist.new
    @playlist = current_user.playlists.build
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    # @playlist = Playlist.new(playlist_params)
    @playlist = current_user.playlists.build(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_song
    pl = Playlist.find(params[:playlist_id]).playlist_songs.create(song: Song.find(params[:song_id]))
    unless pl.valid?
      render plain: pl.errors.full_messages.first
    else
      pl.save
      render plain: 'Song has been added to the playlist'
    end
  end

  def remove
    song = Song.find(params[:song_id])
    playlist = Playlist.find(params[:playlist_id])
    if current_user == playlist.user
      PlaylistSong.find_by(song_id: song.id, playlist_id: playlist.id).destroy
      notice = 'Song removed'
    else
      notice = 'You can only remove song from playlist you own'
    end
    redirect_to playlist_path(playlist)
    flash[:notice] = notice
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:user_id, :name, :description, :image)
    end

    def playlist_owner?
      Playlist.find(params[:id]).user_id == current_user.id
    end

    def check_owner
      unless playlist_owner?
        flash[:notice] = 'You are not authorized to access this page'
        redirect_to :back
      end
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/edit.html.erb
<% @title = "Gestion Playlist" %>
<% if @playlist.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @playlist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <!-- Sidebar -->
  <div class="row row-edit">
    <div class="page-content-edit">
      <div class="head-edit">
        <h1 class="title-head-admin">ADMINISTRATION</h1>
        <%= render partial: "shared/user_badge", locals: {edit: true} %>
        <div class="deconnect-edit">
          <%= image_tag('logout.png') %>
          <span><%= link_to "Deconnexion", logout_path, :method => "delete" %></span>
        </div>
      </div>
      <div class="container-fluid">
        <!-- <img src="img/zikror.png" class="bg-content"> -->
        <div class="row">
          <div class="col-lg-6 col-md-6 content-page-edit col-md-offset-3">
          <h3>Modifier votre playlist<br/><%= link_to 'VOIR', @playlist %></h3>
          <%= form_for(@playlist) do |f| %>
            <%= f.text_field :name, placeholder: 'Ajouter un titre*' %>
            <%= f.text_area :description, placeholder: 'Ajouter une description' %>
            <input type="text" name="" disabled="disabled" id="value-file" class="input-text file" placeholder="Ajouter une image à votre playlist">
            <div class="file-upload">
              <%= image_tag('upload.png') %>
              <%= f.file_field :image, class: 'upload' %>
            </div>
           
            <div class="block-btn-edit">
            <a href="<%= user_path(current_user) %>"><button type="button" class="btn-cancel-account">ANNULER</button></a>
            <%= f.button :VALIDER, value: "VALIDER" %>
            </div>
            <p>*Champ obligatoire </p>
          <% end %>         
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/playlists/index.html.erb
<% @title = "Playlists" %>
 <div class="container container-global">
    <!-- Sidebar -->
    <div class="row">
      <%= render partial: "shared/sidebar" %>

      <div class="page-content">
        <div class="head">
          
          <h1 class="title-head">PARCOURIR</h1>
          <%= render partial: "shared/user_badge" %>
          <%= form_tag('/playlists', method: 'get', class: "form-search form-search-musique") do %>
          <div class="form-group">
            <%= search_field_tag(:playlist_name, params[:playlist_name] || '', list: 'datas', placeholder: "Rechercher une playlist") %>
            <datalist id="datas">
              <% Playlist.pluck(:name).each do |d| %>
                <option value="<%= d %>"></option>
              <% end %>
            </datalist>
            <button type="submit"><%= image_tag('search.png') %></button>
            </div>
          <% end %>

        
        </div>
        <div class="container-fluid">
          <!-- <%= image_tag('zikror.png', class: "bg-content") %> -->
          <div class="row">
            <ul class="nav-profil">
              <li data-content="ctn-musique"><span><%= link_to 'AJOUTER UNE NOUVELLE PLAYLIST', new_playlist_path %></span></li>
              <div class="menu-profil">
                <%= image_tag('menu-show.png', class: "show-img", style:"display:none;") %>
                <%= image_tag('multiply.png', class: "close-img") %>
              </div>
            </ul>
            <div class="col-lg-9 col-md-8 content-page">
              <div class="table ctn-playlist">
              <% @playlists.each do |playlist| %>
                <div class="divider-block-playlist" <% unless playlist.image_file_name.nil? %> style="background: rgb(65, 65, 65) url(<%= playlist.image.url %>) no-repeat 200% center / cover;" <% end %>>
  
                  <a href="<%= playlist_path(playlist) %>">

                  <div class="circle" <% unless playlist.image_file_name.nil? %>style="border:none;"<% end %>>
                    <%= image_tag('search.png') %>
                  </div>
                  </a>
                  <span><%= link_to playlist.name, playlist_path(playlist) %></span><br>
                  <span class="nbr-title"><%= pluralize(playlist.songs.size, 'titre') %></span>
                </div>
              <% end %>
              </div>
            </div>
            <div class="profil-side col-lg-3 col-md-4">
              <%= render partial: "shared/right_sidebar", locals: {user: current_user} %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/playlists/new.html.erb
<% @title = "Ma Playlist" %>
<% if @playlist.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @playlist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <!-- Sidebar -->
  <div class="row row-edit">
    <div class="page-content-edit">
      <div class="head-edit">
        <h1 class="title-head-admin">ADMINISTRATION</h1>
        <%= render partial: "shared/user_badge", locals: {edit: true} %>
        <div class="deconnect-edit">
          <%= image_tag('logout.png') %>
          <span><%= link_to "Deconnexion", logout_path, :method => "delete" %></span>
        </div>
      </div>
      <div class="container-fluid">
        <!-- <img src="img/zikror.png" class="bg-content"> -->
        <div class="row">
          <div class="col-lg-6 col-md-6 content-page-edit col-md-offset-3">
          <h3>Ajouter une playlist</h3>
          <%= form_for(@playlist) do |f| %>
            <%= f.text_field :name, placeholder: 'Ajouter un titre*' %>
            <%= f.text_area :description, placeholder: 'Ajouter une description' %>
            <input type="text" name="" disabled="disabled" id="value-file" class="input-text file" placeholder="Ajouter une pièce jointe">
            <div class="file-upload">
              <%= image_tag('upload.png') %>
              <%= f.file_field :image, class: 'upload' %>
            </div>
           
            <div class="block-btn-edit">
            <a href="<%= user_path(current_user) %>"><button type="button" class="btn-cancel-account">ANNULER</button></a>
            <%= f.button :VALIDER, value: "VALIDER" %>
            </div>
            <p>*Champ obligatoire </p>
          <% end %>         
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/playlists/show.html.erb
<% @title = playlist.name.capitalize %>
<div class="container container-global">

<!-- Sidebar -->
<div class="row">
	<%= render partial: "shared/sidebar" %>
	<div class="page-content">
		<div class="head">
			<%= render partial: "shared/player", locals: {songs: @playlist.songs, continue: true} %>
			<h1 class="title-head"><%= @playlist.user == current_user ? "MA PLAYLIST" : "PLAYLIST DE #{@playlist.user.username}" %></h1>
			<%= render partial: "shared/user_badge" %>
			<%= form_tag('/playlists', method: 'get', class: "form-search form-search-musique") do %>
			<div class="form-group">
			  <%= search_field_tag(:playlist_name, params[:playlist_name] || '', list: 'datas', placeholder: "Rechercher une playlist") %>
			  <datalist id="datas">
			    <% Playlist.pluck(:name).each do |d| %>
			      <option value="<%= d %>"></option>
			    <% end %>
			  </datalist>
			  <button type="submit"><%= image_tag('search.png') %></button>
			  </div>
			<% end %>
		</div>
		<div class="container-fluid">
			<%= image_tag('zikror.png', class: "bg-content") %>
			<div class="row">
				<ul class="nav-profil">
					<li class=""><span><%= link_to 'RETOURNER SUR VOTRE PROFIL', user_path(current_user) %></span></li>
					<li class="parcourir-list"><span><%= link_to 'PARCOURIR LES PLAYLISTS', playlists_path %>	</span></li>
					
					<div class="menu-profil">
						<%= image_tag('menu-show.png', class: "show-img", style:"display:none;") %>
						<%= image_tag('multiply.png', class: "close-img") %>
					</div>
				</ul>
				<div class="col-lg-9 col-md-8 content-page">
					<div class="block-info-playlist">
						<div class="img-playlist" <% unless @playlist.image_file_name.nil? %> style="background: rgb(65, 65, 65) url(<%= @playlist.image.url %>) no-repeat 200% center / cover;" <% end %>>
						<div class="circle" <% unless @playlist.image_file_name.nil? %>style="border:none;"<% end %>>
										
									</div>
						</div>
						<div class="text-info-playlist">
							<h1><%= @playlist.name %>
								<% if owner?(@playlist) %>
									<%= link_to raw(image_tag('new-file.png')), edit_playlist_path(@playlist) %>
								<% end %>
							</h1>
							<p>
								<h4><strong>Description:</strong></h4>
								<%= @playlist.description %>
							</p>
						</div>
					</div>
					<table class="table musique">
						<thead>
							<% unless @playlist.songs.empty? %>
								<%= render partial: "shared/songs_list", locals: {songs: @playlist.songs, playlist: true} %>
							<% else %>
								Aucune chanson n'a été ajouté à cette playlist.
							<% end %>
						</thead>
					</table>
					
				</div>
				<div class="profil-side col-lg-3 col-md-4">
					<%= render partial: "shared/right_sidebar", locals: {user: @playlist.user, data: @playlist.songs} %>
				</div>
			</div>
		</div>
	</div>
</div>
</div>